spring:
  datasource:
    url: jdbc:mysql://mysqldb:3306/api?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    password: Super@3abdou
    username: root
  jpa:
    hibernate.ddl-auto : update
server:
  port : 8081