spring:
  datasource:
    url: jdbc:postgresql://dpg-chbdurqk728tp9dop2s0-a.render.com:5432/api_vh87?createDatabaseIfNotExist=true
    username: root
    password: i4vTcugE71oofKEwoAwedE4KrecCIzao
  jpa:
    hibernate.ddl-auto : update
server:
  port : 8081