spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: jdbc:mysql://databaseServer:3306/api?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    password: Super@3abdou
    username: root
  jpa:
    hibernate.ddl-auto : update
server:
  port : 8081